name: Deploy to GCP Compute Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Compute Engine
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_INSTANCE_IP }}
          username: YOUR_GCP_USERNAME
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/YOUR_PROJECT
            git pull origin main
            sudo systemctl restart myapp
