name: Deploy to GCE

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.22.102.174 >> ~/.ssh/known_hosts

      - name: Deploy to GCE
        run: ssh -i ~/.ssh/id_rsa btsy7331@34.22.102.174 "export HOME=/home/btsy7331 && cd ~/SRIM_PROD && bash deploy.sh"